all: ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9 ex10 ex11 ex12 ex13 ex131 ex133 ex14 ex142 ex15 ex15e1 ex15e3 ex15h1 ex15h2 ex15h6 ex15h7 ex15h8 ex16 ex16e1 ex16e3 ex16e4 ex16h1 ex17 ex17e1

ex1: ex1.c
	gcc $(CFLAGS) -o ex1 ex1.c
	./ex1

ex3: ex3.c
	gcc $(CFLAGS) -o ex3 ex3.c
	./ex3

ex4: ex4.c
	gcc $(CFLAGS) -o ex4 ex4.c

ex5: ex5.c
	gcc $(CFLAGS) -o ex5 ex5.c

ex6: ex6.c
	gcc $(CFLAGS) -o ex6 ex6.c

ex7: ex7.c
	gcc $(CFLAGS) -o ex7 ex7.c

ex8: ex8.c
	gcc $(CFLAGS) -o ex8 ex8.c

ex9: ex9.c
	gcc $(CFLAGS) -o ex9 ex9.c
	./ex9

ex10: ex10.c
	gcc $(CFLAGS) -o ex10 ex10.c

ex11: ex11.c
	gcc $(CFLAGS) -o ex11 ex11.c

ex12: ex12.c
	gcc $(CFLAGS) -o ex12 ex12.c

ex13: ex13.c
	gcc $(CFLAGS) -o ex13 ex13.c

ex131: ex131.c
	gcc $(CFLAGS) -o ex131 ex131.c

ex133: ex133.c
	gcc $(CFLAGS) -o ex133 ex133.c

ex14: ex14.c
	gcc $(CFLAGS) -o ex14 ex14.c

ex142: ex142.c
	gcc $(CFLAGS) -o ex142 ex142.c

ex15: ex15.c
	gcc $(CFLAGS) -o ex15 ex15.c

ex15e1: ex15e1.c
	gcc $(CFLAGS) -o ex15e1 ex15e1.c

ex15e3: ex15e3.c
	gcc $(CFLAGS) -o ex15e3 ex15e3.c

ex15h1: ex15h1.c
	gcc $(CFLAGS) -o ex15h1 ex15h1.c

ex15h2: ex15h2.c
	gcc $(CFLAGS) -o ex15h2 ex15h2.c

ex15h6: ex15h6.c
	gcc $(CFLAGS) -o ex15h6 ex15h6.c

ex15h7: ex15h7.c
	gcc $(CFLAGS) -o ex15h7 ex15h7.c

ex15h8: ex15h8.c
	gcc $(CFLAGS) -o ex15h8 ex15h8.c

ex16: ex16.c
	gcc $(CFLAGS) -o ex16 ex16.c

ex16e1: ex16e1.c
	gcc $(CFLAGS) -o ex16e1 ex16e1.c

ex16e3: ex16e3.c
	gcc $(CFLAGS) -o ex16e3 ex16e3.c

ex16e4: ex16e4.c
	gcc $(CFLAGS) -o ex16e4 ex16e4.c

ex16h1: ex16h1.c
	gcc $(CFLAGS) -o ex16h1 ex16h1.c

ex17: ex17.c
	gcc $(CFLAGS) -o ex17 ex17.c

ex17e1: ex17e1.c
	gcc $(CFLAGS) -o ex17e1 ex17e1.c

CFLAGS=-Wall -g3 -O0

clean:
	rm -f ex1
	rm -f ex3
	rm -f ex4
	rm -f ex5
	rm -f ex6
	rm -f ex7
	rm -f ex8
	rm -f ex9
	rm -f ex10
	rm -f ex11
	rm -f ex12
	rm -f ex13
	rm -f ex131
	rm -f ex133
	rm -f ex14
	rm -f ex142
	rm -f ex15
	rm -f ex15e1
	rm -f ex15e3
	rm -f ex15h1
	rm -f ex15h2
	rm -f ex15h6
	rm -f ex15h7
	rm -f ex15h8
	rm -f ex16
	rm -f ex16e1
	rm -f ex16e3
	rm -f ex16e4
	rm -f ex16h1
	rm -f ex17
	rm -f ex17e1
