all: ex17 ex17h7 stack

ex17: ex17.c
	gcc $(CFLAGS) -o ex17 ex17.c

stack: stack.c
	gcc $(CFLAGS) -o stack stack.c

CFLAGS=-Wall -g3 -O0

ex17h7: ex17h7.c
	gcc $(CFLAGS) -o ex17h7 ex17h7.c

clean:
	rm -f ex17
	rm -f ex17h7
	rm -f stack
