all: ex18 ex18e1 ex18h3 ex18h4

ex18: ex18.c
	gcc $(CFLAGS) -o ex18 ex18.c

ex18e1: ex18e1.c
	gcc $(CFLAGS) -o ex18e1 ex18e1.c

ex18h3: ex18h3.c
	gcc $(CFLAGS) -o ex18h3 ex18h3.c

ex18h4: ex18h4.c
	gcc $(CFLAGS) -o ex18h4 ex18h4.c

CFLAGS=-Wall -g3 -O0

clean:
	rm -f ex18
	rm -f ex18e1
	rm -f ex18h3
	rm -f ex18h4
